library: library.db
#Example Comment beneath Library
import_write: true
import_copy: true
import_move: false
import_resume: true
import_incremental: true
import_quiet_fallback: false
import_timid: false
import_log:

ignore: [".*", "*~"]
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
art_filename: cover

plugins: []
pluginpath: []
threaded: true
color: true
timeout: 5.0
per_disc_numbering: false
verbose: false

list_format_item: $artist - $album - $title
list_format_album: $albumartist - $album

paths:
    directory: ~/Music
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

# This
# Thisssss
#is: awesome!